# Generated by Django 4.1.7 on 2023-03-02 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('insee_code', models.CharField(max_length=5, null=True)),
                ('zip_code', models.CharField(max_length=5, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('gps_lat', models.DecimalField(decimal_places=14, max_digits=16)),
                ('gps_lng', models.DecimalField(decimal_places=14, max_digits=17)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.cities')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_place_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_name', models.CharField(max_length=50)),
                ('specialist_name', models.CharField(max_length=50)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.place')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.speciality')),
                ('type_review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.typereview')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('speciality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.speciality')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='type_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.typeplace'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doclink', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.appointment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.profile')),
                ('type_document_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.typedocument')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.CharField(max_length=255)),
                ('region', models.ForeignKey(db_column='region_code', on_delete=django.db.models.deletion.CASCADE, to='patient.region')),
            ],
        ),
        migrations.AddField(
            model_name='cities',
            name='department_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.department'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.profile'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.review'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='specialist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.speciality'),
        ),
    ]
