# Generated by Django 4.1.7 on 2023-03-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_document_appointment_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.speciality'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='speciality_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.specialityname'),
        ),
    ]
