# Generated by Django 4.1.7 on 2023-03-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_specialityname_alter_profile_speciality_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
    ]
