# Generated by Django 4.1.7 on 2023-03-10 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_remove_profile_email_remove_profile_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.appointment'),
        ),
    ]
